name: TapToDo-LEET.CC
main: LEET_CC\TapToDo
version: 1.0.0
authors: [Falk, 64FF00]
api: [1.0.0]
load: POSTWORLD
commands:
  action:
    permission: ttdleet.command
    description: Adds a new command to a block
    usage: /action
permissions:
  ttdleet:
    default: op
    children:
      ttdleet.command: []
      ttdleet.tap:
      default: true