name: MNetwork-Tap
main: LEET_CC\TapToDo
version: 1.0.0
authors: [SheepDev]
api: [1.0.0,2.0.0]
load: POSTWORLD
commands:
  action:
    permission: ttdleet.command.action
    description: Adds a new command to a block
    usage: /action
  actionDelAll:
    permission: ttdleet.command.actionDelAll
    description: Removes all actions assigned to the block
    usage: /actionDelAll
permissions:
  ttdleet:
    default: op
    children:
      ttdleet.command:
        children:
          ttdleet.command.action:
            default: op
          ttdleet.command.actionDelAll:
            default: op  
      ttdleet.tap:
        default: true
